
services:
  drupal:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: drupal
    ports:
      - "8080:80"
    depends_on:
      - mariadb
    environment:
      DRUPAL_DB_HOST: mariadb
      DRUPAL_DB_PORT: 3306
      DRUPAL_DB_NAME: drupal
      DRUPAL_DB_USER: drupal
      DRUPAL_DB_PASSWORD: drupal

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    volumes:
      - mariadb-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: rootpassword

volumes:
  drupal-data:
  mariadb-data: